### ISSUE TITLE
Send welcome email to newly registered SME admins

### ISSUE THREAD

**Issue by starkmsu** [OpenMAVN/MAVN.Service.AdminManagement#21]
If newly created admin user has only PartnerEdit permission for ProgramPartners type then it's a SME admin, so we need to send a welcome email for them.
Need to have a separate email for SME admins and not use usual AdminCreatedEmail.

About email templates ids - see comment below

**Comment by vitaliidasaev** [comment]
emailTemplateId: `admin-welcome-email`
the url variable inside template: `${PartnersUrl}`
it should be combined the same way as `${EmailVerificationLink}` of `admin-created-email` but instead of `VerificationLinkPath` use `PartnersLinkPath`: `/admin/platform/partners`
