### ISSUE TITLE
Define AdminEmailVeridfied in Contract project

### ISSUE THREAD

**Issue by starkmsu** [OpenMAVN/MAVN.Service.AdminManagement#9]
Add to MAVN.Service.AdminManagement.Contract.Events
public class AdminEmailVeridfied
{
        public string AdminId { get; set; }
        public DateTime TimeStamp { get; set; }
}

**Comment by vitaliidasaev** [comment]
published MAVN.Service.AdminManagement.Contract.1.1.0
